export interface ProfileResponse {
  id: string,
  email: string,
  username: string,
  provincia: string,
  years: string,
  typeRel: string,
  sport: string,
  art: string,
  politic: string,
  wantSons: string,
  haveSons: string,
  gender: string,
  photo: string,
  description: string,
  conected: string,
  active: string,
}
